

[envs.reaching-defs]
command = """
bril2json < {filename} | ../../target/debug/reaching-defs
"""
output."reaching-defs.dot" = "-"

[envs.live-vars]
command = """
bril2json < {filename} | ../../target/debug/live-vars
"""
output."live-vars.dot" = "-"

[envs.const-prop]
command = """
bril2json < {filename} | ../../target/debug/const-prop
"""
output."const-prop.dot" = "-"

[envs.available-expr]
command = """
bril2json < {filename} | ../../target/debug/available-expr
"""
output."available-expr.dot" = "-"

[envs.interval]
command = """
bril2json < {filename} | ./interval.py
"""
output.interval = "-"
