

[envs.reaching-defs]
command = """
bril2json < {filename} | ../../target/debug/reaching-defs
"""
output."reaching-defs.dot" = "-"

[envs.live-vars]
command = """
bril2json < {filename} | ./live-vars.py
"""
output.live-vars = "-"
[envs.interval]
command = """
bril2json < {filename} | ./interval.py
"""
output.interval = "-"

[envs.const-prop]
command = """
bril2json < {filename} | ./const-prop.py
"""
output.const-prop = "-"

[envs.available-expr]
command = """
bril2json < {filename} | ./available-expr.py
"""
output.available-expr = "-"
