extract = 'total_dyn_inst: (\d+)'
benchmarks = [
    'bril/benchmarks/*/*.bril',
    'lessons/*/test/*.bril',
    'playground/*.bril',
]

[runs.baseline]
pipeline = ["bril2json", "brilirs -p {args}"]
timeout = 100

[runs.opt]
pipeline = [
    "bril2json",
    "target/release/lvn",
    "target/release/tdce",
    "brilirs -p {args}",
]
timeout = 100
