extract = 'total_dyn_inst: (\d+)'
benchmarks = 'bril/benchmarks/*/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.opt]
pipeline = [
    "bril2json",
    "lessons/3/lvn.py",
    "lessons/3/trivial-dce.py",
    "brili -p {args}",
]