extract = 'total_dyn_inst: (\d+)'
benchmarks = ['bril/benchmarks/*/*.bril']

[runs.baseline]
pipeline = ["bril2json", "brilirs -p {args}"]
timeout = 100

[runs.lvn-dce]
pipeline = [
    "bril2json",
    "target/release/lvn",
    "target/release/tdce",
    "brilirs -p {args}",
]

[runs.ssa]
pipeline = ["bril2json", "target/debug/to-ssa", "brilirs -p {args}"]

[runs.ssa-roundtrip]
pipeline = [
    "bril2json",
    "target/debug/to-ssa",
    "target/debug/from-ssa",
    "brilirs -p {args}",
]

[runs.trace-speculation]
pipeline = ["bril2json", "target/debug/brilitrace {args}", "brili -p {args}"]

timeout = 100
