[workspace]
members = ["utils", "lessons/3"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
bril-rs = { path = "bril/bril-rs", features = [
  "memory",
  "float",
  "ssa",
  "speculate",
  "position",
  "import",
  "char",
] }
utils = { version = "0.0.1", path = "utils" }
serde = "1.0.217"
