[envs.test]
command = """
bril2json < {filename} | brili {args}
"""
output.expect = "-"

[envs.insn-counter]
command = """
./lessons/2/insn-counter.py --file {filename} | brili {args}
"""
output.insn-counted = "-"

[envs.trivial-dce]
command = """
bril2json < {filename} | ./lessons/3/trivial-dce.py | bril2txt
"""
output.trivial-dce = "-"

[envs.lvn]
command = """
bril2json < {filename} | ./lessons/3/lvn.py | bril2txt
"""
output.lvn = "-"

[envs.lvn-dce]
command = """
bril2json < {filename} | ./lessons/3/lvn.py | ./lessons/3/trivial-dce.py | bril2txt
"""
output.lvn-dce = "-"


[envs.diagnostics]
command = """
bril2json < {filename} | ./playground/diagnostics.py
"""
output.diagnostics = "-"