[envs.test]
command = """
bril2json < {filename} | brilirs -p {args}
"""
output.expect = "-"
output.prof = "2"

[envs.insn-counter]
command = """
./lessons/2/insn-counter.py --file {filename} | brilirs {args}
"""
output.insn-counted = "-"

[envs.trivial-dce]
command = """
bril2json < {filename} | ./lessons/3/trivial-dce.py | bril2txt
"""
output.trivial-dce = "-"

[envs.lvn]
command = """
bril2json < {filename} | ./lessons/3/lvn.py | bril2txt
"""
output.lvn = "-"

[envs.lvn-dce]
command = """
utils/pipeline.sh lessons/3/lvn.py lessons/3/trivial-dce.py < {filename} | bril2txt
"""
output.lvn-dce = "-"

[envs.opt]
command = """
utils/pipeline.sh lessons/3/lvn.py lessons/3/trivial-dce.py < {filename} | bril2txt
"""
output.opt = "-"

[envs.diagnostics]
command = """
bril2json < {filename} | ./playground/diagnostics.py
"""
output.diagnostics = "-"