[envs.skeleton]
command = """
clang -O0 -fpass-plugin=../../build/lessons/7/SkeletonPass.so {filename} -o /dev/null
"""
output.skeleton = "2"

[envs.blockdisplay-ll]
command = """
clang -O0 -fpass-plugin=../../build/lessons/7/BlockDisplayPass.so {filename} -emit-llvm -S -o /dev/stdout
"""
output."blockdisplay.ll" = "-"

[envs.blockdisplay]
command = """
clang -O0 -fpass-plugin=../../build/lessons/7/BlockDisplayPass.so {filename} ../../build/lessons/7/libBlockDisplayRT.a -o {base}.tmpout && ./{base}.tmpout && rm {base}.tmpout
"""
output.blockdisplay = "-"