[package]
name = "lesson-6"
version = "0.0.1"
edition.workspace = true

[dependencies]
bril-rs.workspace = true
utils.workspace = true
log.workspace = true
graphviz-rust.workspace = true
itertools.workspace = true
linked-hash-map.workspace = true
linked_hash_set.workspace = true
