[envs.ssa]
command = """
bril2json < {filename} | ../../target/debug/to-ssa | bril2txt
"""
output."ssa" = "-"

[envs.check-ssa]
command = """
bril2json < {filename} | ../../target/debug/to-ssa | brilirs -p {args}
"""
output.expect = "-"


[envs.ssa-roundtrip]
command = """
bril2json < {filename} | ../../target/debug/to-ssa | ../../target/debug/from-ssa | bril2txt
"""
output.ssa-roundtrip = "-"

[envs.check-roundtrip]
command = """
bril2json < {filename} | ../../target/debug/to-ssa | ../../target/debug/from-ssa | brilirs -p {args}
"""
output.expect = "-"

[envs.is-ssa]
command = """
bril2json < {filename} | ../../target/debug/to-ssa | ../../target/debug/is-ssa
"""
return_code = 0
